### ISSUE TITLE
Wrong oAuth parameters

### ISSUE THREAD

**Issue by jes-carr** [TimNZ/node-xero#1]
I'm trying to build a PrivateApp, and I'm always getting the error 'Token has not been provided'. 

After digging a bit I found that in application.js the `get` and `putOrPost` functions you are sending as parameter `this.options.accessToken` and `this.options.accessSecret`, which are `undefined`. 

As a quick fix I changed it to `this.options.consumerKey`, `this.options.consumerSecret`, and now the authorisation works.

**Comment by TimNZ** [comment]
Thanks, I'll do an update soon.

**Comment by TimNZ** [comment]
Xero are now using this sdk as the base for the official nodejs SDK, so it's getting new love.

https://github.com/XeroAPI/xero-node
